/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#a03f28",
        "primary-container": "#c0573e",
        "on-primary": "#ffffff",
        "on-primary-container": "#120100",
        "primary-fixed": "#ffdad2",
        "primary-fixed-dim": "#ffb4a3",
        "on-primary-fixed": "#3d0700",
        "on-primary-fixed-variant": "#812914",
        "secondary": "#4c56af",
        "secondary-container": "#959efd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#27308a",
        "secondary-fixed": "#e0e0ff",
        "secondary-fixed-dim": "#bdc2ff",
        "on-secondary-fixed": "#000767",
        "on-secondary-fixed-variant": "#343d96",
        "tertiary": "#825400",
        "tertiary-container": "#a36b04",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffffff",
        "tertiary-fixed": "#ffddb4",
        "tertiary-fixed-dim": "#feb956",
        "on-tertiary-fixed": "#291800",
        "on-tertiary-fixed-variant": "#633f00",
        "background": "#fcf9f6",
        "on-background": "#1c1c1a",
        "surface": "#fcf9f6",
        "on-surface": "#1c1c1a",
        "surface-variant": "#e5e2df",
        "on-surface-variant": "#56423d",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f0",
        "surface-container": "#f0edea",
        "surface-container-high": "#eae8e5",
        "surface-container-highest": "#e5e2df",
        "surface-bright": "#fcf9f6",
        "surface-dim": "#dcdad7",
        "surface-tint": "#a03f29",
        "outline": "#8a726c",
        "outline-variant": "#ddc0ba",
        "inverse-surface": "#31302f",
        "inverse-on-surface": "#f3f0ed",
        "inverse-primary": "#ffb4a3",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};
