// Run: node scripts/fixImages.mjs
// Checks TheMealDB image URLs and replaces broken ones with working Unsplash images

import { writeFileSync, readFileSync } from 'fs';

// Curated Unsplash food images by cuisine/category keyword
const FALLBACK_IMAGES = [
  'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80', // pizza
  'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80', // biryani
  'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80', // ramen
  'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80', // tacos
  'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&q=80', // curry
  'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800&q=80', // pad thai
  'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&q=80', // croissant
  'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&q=80', // pasta
  'https://images.unsplash.com/photo-1590412200988-a436970781fa?w=800&q=80', // shakshuka
  'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&q=80', // pho
  'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80', // tagine
  'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=800&q=80', // bibimbap
  'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80', // indian food
  'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800&q=80', // chole
  'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80', // dosa
  'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&q=80', // tandoori
  'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80', // dal
  'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800&q=80', // chinese
  'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80', // dim sum
  'https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80', // sushi
  'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80', // cacio e pepe
  'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&q=80', // mole
  'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80', // injera
  'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=800&q=80', // hummus
  'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80', // salad
  'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80', // food bowl
  'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80', // grilled
  'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80', // dessert
  'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800&q=80', // breakfast
  'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80', // seafood
];

async function checkUrl(url) {
  try {
    const r = await fetch(url, { method: 'HEAD', signal: AbortSignal.timeout(5000) });
    return r.ok;
  } catch {
    return false;
  }
}

async function run() {
  const content = readFileSync('lib/mockData.ts', 'utf8');
  
  // Extract the JSON array
  const match = content.match(/export const MOCK_RECIPES = (\[[\s\S]*?\]);\s*\nexport/);
  if (!match) { console.error('Could not parse mockData.ts'); process.exit(1); }
  
  const recipes = JSON.parse(match[1]);
  console.log(`Checking ${recipes.length} recipes...`);
  
  let fixed = 0;
  let imgIdx = 0;
  
  // Check a sample of URLs (first 20 to see if TheMealDB is broken)
  const sample = recipes.slice(0, 5);
  for (const r of sample) {
    const ok = await checkUrl(r.coverImageUrl);
    console.log(`${r.title}: ${r.coverImageUrl.substring(0, 60)}... → ${ok ? '✓' : '✗ BROKEN'}`);
    if (!ok) {
      // Replace all TheMealDB URLs since they're all broken
      console.log('\nTheMealDB images are broken. Replacing all with Unsplash...');
      for (const recipe of recipes) {
        if (recipe.coverImageUrl?.includes('themealdb.com')) {
          recipe.coverImageUrl = FALLBACK_IMAGES[imgIdx % FALLBACK_IMAGES.length];
          imgIdx++;
          fixed++;
        }
      }
      break;
    }
  }
  
  if (fixed > 0) {
    console.log(`\nFixed ${fixed} broken images`);
    const output = `// AUTO-GENERATED by scripts/fetchMeals.mjs — do not edit manually
// ${recipes.length} recipes from TheMealDB + curated extras

export const MOCK_RECIPES = ${JSON.stringify(recipes, null, 2)};

export const MOCK_TOTAL = ${recipes.length};
`;
    writeFileSync('lib/mockData.ts', output);
    console.log('Written to lib/mockData.ts');
  } else {
    console.log('All images OK — no fixes needed');
  }
}

run().catch(console.error);
